# Generated by Django 4.0 on 2022-01-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0009_rename_instansiasal_pic_instansi_asal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keterangan',
            name='keterangan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='nama_role',
            field=models.CharField(max_length=50),
        ),
    ]
