# Generated by Django 4.0 on 2022-01-24 07:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0010_alter_keterangan_keterangan_alter_role_nama_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surat',
            name='pic_id',
        ),
        migrations.AddField(
            model_name='surat',
            name='email_pic',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='id_pic',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='instansi_asal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='kontak_pic',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='surat',
            name='nama_pic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
