# Generated by Django 4.0 on 2022-01-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0011_remove_surat_pic_id_surat_email_pic_surat_id_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='id_pic',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
